name: ci

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-26.04
    env:
      GARE_REQUIRE_PODMAN: "1"
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: check podman
        run: |
          podman --version
          podman kube play --service-container=true --service-exit-code-propagation=any --help
      - name: test
        run: go test -v -race ./...
